In [12]:
# Task 3.1 [5]
from pymongo import MongoClient
import pymongo
import csv

def readfile(filename):
    results = []
    file = open(filename)
    csvreader = csv.reader(file)
    for row in csvreader:
        results.append(row)
    return results

def Task3_1():
    client = pymongo.MongoClient("127.0.0.1", 27017)
    client.drop_database("school")
    mydb = client['school']
    mycol = client['school']['teacher']
    
    results = readfile("teachers.csv")

    for i in range(1, len(results)):
        document = {} 
        if results[i][0] != "":
            document[results[0][0]] = int(results[i][0])
        if results[i][1] != "":
            document[results[0][1]] = results[i][1]
        if results[i][2] != "":
            document[results[0][2]] = results[i][2]
        if results[i][3] != "":
            document[results[0][3]] = results[i][3]
        if results[i][4] != "":
            document[results[0][4]] = results[i][4]
        if results[i][5] != "":
            document[results[0][5]] = int(results[i][5])
            
        # Insert data into database
        mycol.insert_one(document)
    client.close()


Task3_1()

In [13]:
# Task 3.2 - display_all_teacher_details [3]
def Task_3_2(): 
    client = pymongo.MongoClient("127.0.0.1", 27017)
    mydb = client['school']
    mycol = client['school']['teacher']

    query = {}
    data = list(mycol.find(query))
    client.close()
    
    print("{:<5}{:<20}{:<15}{:<10}{:<20}{:<7}".format("_id","Name","Department","Contact","Role","Ratings"))
    for row in data:
        print("{:<5}{:<20}{:<15}{:<10}{:<20}{:<7}".format(row["_id"],
                                                          row["Name"],
                                                          row["Department"],
                                                          row["Contact"] if ("Contact" in row) else "-",
                                                          row["Role"] if ("Role" in row) else "-",
                                                          row["Ratings"] if ("Ratings" in row) else "-"))


Task_3_2()

_id  Name                Department     Contact   Role                Ratings
1    Rufus Schuck        English        80012010  PaperCoordinator    3299
2    Ione Wolfe          Chemistry      80567822  Invigilator         2639
3    Hillary Curl        Maths          81123632  Invigilator         1773
4    Juli Barnhill       Computing      81671234  -                   2696
5    Tashia Bowen        English        82235254  Relief              1629
6    Marguerita Mciver   Physics        82791568  RestroomDuty        4375
7    Sharie Schall       Maths          83346876  -                   2704
8    Paris Curington     Biology        83902687  PaperCoordinator    3709
9    Ashely Faye         English        84458498  Invigilator         3707
10   Elvia Dubrey        Chemistry      -         Invigilator         -
11   Terrence Shannon    Maths          -         Invigilator         2357
12   Carolann Kintner    Chemistry      86156875  Relief              1555
13   So Atkins           Maths          86681742  RestroomDuty        2525
14   Kathlene Collar     English        87237553  Reserve             1814
15   Luanne Lett         Music          -         PaperCoordinator    1962
16   Ola Markell         Maths          88349175  Invigilator         3831
17   Claudette Bode      Chemistry      88904986  Invigilator         1699
18   Lashawna Meals      Maths          89460797  Invigilator         3555
19   Angle Linck         English        -         Relief              3485
20   Toney Mcnab         Physics        90023100  RestroomDuty        3420
21   Hertha Dossantos    Maths          90029592  Reserve             2281
22   Jalisa Stoudemire   Biology        90036084  -                   3388
23   Johnna Lecuyer      English        90042576  Invigilator         2640
24   Grazyna Kitzman     Maths          -         Invigilator         1804
25   Phyliss Rolen       English        90055560  -                   4011
26   Shaunda Sieg        Economics      90062052  RestroomDuty        1755
27   Abdul Boland        Chemistry      90068544  Reserve             3743
28   Lai Lazard          Maths          90075036  -                   2018
29   Chadwick Griffin    Chemistry      90081528  Invigilator         4139
30   Jaye Galle          Maths          90088020  -                   4042
31   Virgilio Britt      Physics        90094512  Relief              4056
32   Lanita Sciortino    Maths          90420932  RestroomDuty        3567
33   See Borne           Biology        90747352  Reserve             1576
34   Laverna Halpern     English        91073772  PaperCoordinator    1545
35   Russell Gillison    Music          -         Invigilator         2719
36   Joella Wessner      Physics        91726612  Invigilator         3117
37   Fredricka Gormley   Maths          92053032  Relief              -
38   Marg Thorington     Chemistry      92379452  -                   4326
39   Odis Levalley       Maths          92705872  Reserve             4498
40   Teodoro Negrin      Chemistry      93032292  PaperCoordinator    4466
41   Tobias Kimmer       Maths          93358712  Invigilator         3463
42   Maryam Brosius      Chemistry      -         -                   -
43   Darlena Crimi       Maths          94011552  Relief              3521
44   Marcella Daigneault Computing      94337972  RestroomDuty        2301
45   Dannette Raasch     English        94664392  -                   2516
46   Farah Quon          Physics        94990812  PaperCoordinator    2565
47   Apryl Soileau       Maths          -         Invigilator         2914
48   Reiko Stack         Biology        95643652  Relief              -
49   Terrance Lauterbach Chemistry      95970072  RestroomDuty        1782
50   Carola Tegeler      Maths          99239291  Reserve             3988

In [17]:
# Task 3.3 [2]
# display the names of teachers who Either 1) do not have both Contact and Role OR 
#                                          2) do not have a Role and is in the Math Department

def Task_3_3():
    client = pymongo.MongoClient("127.0.0.1", 27017)
    mydb = client['school']
    mycol = client['school']['teacher']
    
    query = {"$or":[{"$and":[{"Contact":{"$exists": 0}},{"Role":{"$exists": 0}}]},
                    {"$and":[{'Ratings': {'$lt': 1600}}]}]}
    display = {'_id':1, 'Name':1}
    data = list(mycol.find(query, display))
    client.close()
    
    for row in data:
        #_id,Name,Department,Contact,Role,Ratings
        print("{:<5}{:<20}".format(row["_id"], row["Name"]))

Task_3_3()

12   Carolann Kintner
33   See Borne
34   Laverna Halpern
42   Maryam Brosius

In [15]:
# Task 3.5 [2]
# Change 1 Teacher from Physics to Computing department

def Task_3_4():
    client = pymongo.MongoClient("127.0.0.1", 27017)
    mydb = client['school']
    mycol = client['school']['teacher']
    
    query = {"Department":"Physics"}
    update_one = {"$set":{"Department":"Computing"}}
    mycol.update_one(query, update_one)
    client.close()

Task_3_4()

In [16]:
Task_3_2()

_id  Name                Department     Contact   Role                Ratings
1    Rufus Schuck        English        80012010  PaperCoordinator    3299
2    Ione Wolfe          Chemistry      80567822  Invigilator         2639
3    Hillary Curl        Maths          81123632  Invigilator         1773
4    Juli Barnhill       Computing      81671234  -                   2696
5    Tashia Bowen        English        82235254  Relief              1629
6    Marguerita Mciver   Computing      82791568  RestroomDuty        4375
7    Sharie Schall       Maths          83346876  -                   2704
8    Paris Curington     Biology        83902687  PaperCoordinator    3709
9    Ashely Faye         English        84458498  Invigilator         3707
10   Elvia Dubrey        Chemistry      -         Invigilator         -
11   Terrence Shannon    Maths          -         Invigilator         2357
12   Carolann Kintner    Chemistry      86156875  Relief              1555
13   So Atkins           Maths          86681742  RestroomDuty        2525
14   Kathlene Collar     English        87237553  Reserve             1814
15   Luanne Lett         Music          -         PaperCoordinator    1962
16   Ola Markell         Maths          88349175  Invigilator         3831
17   Claudette Bode      Chemistry      88904986  Invigilator         1699
18   Lashawna Meals      Maths          89460797  Invigilator         3555
19   Angle Linck         English        -         Relief              3485
20   Toney Mcnab         Physics        90023100  RestroomDuty        3420
21   Hertha Dossantos    Maths          90029592  Reserve             2281
22   Jalisa Stoudemire   Biology        90036084  -                   3388
23   Johnna Lecuyer      English        90042576  Invigilator         2640
24   Grazyna Kitzman     Maths          -         Invigilator         1804
25   Phyliss Rolen       English        90055560  -                   4011
26   Shaunda Sieg        Economics      90062052  RestroomDuty        1755
27   Abdul Boland        Chemistry      90068544  Reserve             3743
28   Lai Lazard          Maths          90075036  -                   2018
29   Chadwick Griffin    Chemistry      90081528  Invigilator         4139
30   Jaye Galle          Maths          90088020  -                   4042
31   Virgilio Britt      Physics        90094512  Relief              4056
32   Lanita Sciortino    Maths          90420932  RestroomDuty        3567
33   See Borne           Biology        90747352  Reserve             1576
34   Laverna Halpern     English        91073772  PaperCoordinator    1545
35   Russell Gillison    Music          -         Invigilator         2719
36   Joella Wessner      Physics        91726612  Invigilator         3117
37   Fredricka Gormley   Maths          92053032  Relief              -
38   Marg Thorington     Chemistry      92379452  -                   4326
39   Odis Levalley       Maths          92705872  Reserve             4498
40   Teodoro Negrin      Chemistry      93032292  PaperCoordinator    4466
41   Tobias Kimmer       Maths          93358712  Invigilator         3463
42   Maryam Brosius      Chemistry      -         -                   -
43   Darlena Crimi       Maths          94011552  Relief              3521
44   Marcella Daigneault Computing      94337972  RestroomDuty        2301
45   Dannette Raasch     English        94664392  -                   2516
46   Farah Quon          Physics        94990812  PaperCoordinator    2565
47   Apryl Soileau       Maths          -         Invigilator         2914
48   Reiko Stack         Biology        95643652  Relief              -
49   Terrance Lauterbach Chemistry      95970072  RestroomDuty        1782
50   Carola Tegeler      Maths          99239291  Reserve             3988